export const weatherCodeIcons = {
  0: { label: "Ясно", icon: "/assets/weather-icons/0-clear.svg" },
  1: { label: "Преимущественно ясно", icon: "/weather-icons/1-mainly-clear.svg" },
  2: { label: "Переменная облачность", icon: "/weather-icons/2-partly-cloudy.svg" },
  3: { label: "Пасмурно", icon: "/weather-icons/3-overcast.svg" },
  45: { label: "Туман", icon: "/weather-icons/45-fog.svg" },
  48: { label: "Изморозь, туман", icon: "/weather-icons/48-rime-fog.svg" },
  51: { label: "Слабая морось", icon: "/weather-icons/51-drizzle-light.svg" },
  53: { label: "Умеренная морось", icon: "/weather-icons/53-drizzle-moderate.svg" },
  55: { label: "Сильная морось", icon: "/weather-icons/55-drizzle-heavy.svg" },
  56: { label: "Слабая ледяная морось", icon: "/weather-icons/56-freezing-drizzle-light.svg" },
  57: { label: "Сильная ледяная морось", icon: "/weather-icons/57-freezing-drizzle-heavy.svg" },
  61: { label: "Небольшой дождь", icon: "/weather-icons/61-rain-light.svg" },
  63: { label: "Умеренный дождь", icon: "/weather-icons/63-rain-moderate.svg" },
  65: { label: "Сильный дождь", icon: "/weather-icons/65-rain-heavy.svg" },
  66: { label: "Слабый ледяной дождь", icon: "/weather-icons/66-freezing-rain-light.svg" },
  67: { label: "Сильный ледяной дождь", icon: "/weather-icons/67-freezing-rain-heavy.svg" },
  71: { label: "Небольшой снег", icon: "/weather-icons/71-snow-light.svg" },
  73: { label: "Умеренный снег", icon: "/weather-icons/73-snow-moderate.svg" },
  75: { label: "Сильный снег", icon: "/weather-icons/75-snow-heavy.svg" },
  77: { label: "Снежные зерна", icon: "/weather-icons/77-snow-grains.svg" },
  80: { label: "Небольшие ливни", icon: "/weather-icons/80-rain-showers-light.svg" },
  81: { label: "Умеренные ливни", icon: "/weather-icons/81-rain-showers-moderate.svg" },
  82: { label: "Сильные ливни", icon: "/weather-icons/82-rain-showers-heavy.svg" },
  85: { label: "Небольшой снегопад", icon: "/weather-icons/85-snow-showers-light.svg" },
  86: { label: "Сильный снегопад", icon: "/weather-icons/86-snow-showers-heavy.svg" },
  95: { label: "Гроза", icon: "/weather-icons/95-thunderstorm.svg" },
  96: { label: "Гроза с небольшим градом", icon: "/weather-icons/96-thunderstorm-hail-light.svg" },
  99: { label: "Гроза с сильным градом", icon: "/weather-icons/99-thunderstorm-hail-heavy.svg" }
};
